// <auto-generated />
using System;
using LecturerManagement.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LecturerManagement.Core.Migrations
{
    [DbContext(typeof(LecturerManagementSystemDbContext))]
    [Migration("20220124100035_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerID")
                        .IsUnique()
                        .HasFilter("[LecturerID] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.AdvancedLearning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerID");

                    b.ToTable("AdvancedLearnings");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormsOfTraining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfStudent")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrainingSystemID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSystemID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.DynamicClassFactor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromDynamic")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeachesForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToDynamic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DynamicClassFactors");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.GraduationThesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MarkSessionNumbers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RebuttalProjectNumbers")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TopicNumbers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassID");

                    b.HasIndex("LecturerID");

                    b.ToTable("GraduationTheses");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Lecturer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AcademicLevel")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StandardTimeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectDepartmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YearStartWork")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.HasIndex("StandardTimeID");

                    b.HasIndex("SubjectDepartmentID");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.LecturerScientificResearch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelOfResearch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("YearOfResearchParticipation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerID");

                    b.ToTable("LecturerScientificResearches");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.MachineRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QantityRoom")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerID");

                    b.ToTable("MachineRooms");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.ScientificResearchGuide", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerID");

                    b.ToTable("ScientificResearchGuides");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.StandardTime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardHours")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StandardTimes");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingSystemID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTypeID");

                    b.HasIndex("TrainingSystemID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.SubjectDepartment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubjectDepartments");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.SubjectType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubjectTypes");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Teaching", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LectureID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID", "LectureID", "ClassID");

                    b.HasIndex("ClassID");

                    b.HasIndex("LectureID");

                    b.ToTable("Teachings");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.TrainingSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLearningUnit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingSystems");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Account", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithOne("Account")
                        .HasForeignKey("LecturerManagement.Core.Models.Entities.Account", "LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.AdvancedLearning", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("AdvancedLearnings")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Class", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.TrainingSystem", "TrainingSystem")
                        .WithMany("Classes")
                        .HasForeignKey("TrainingSystemID");

                    b.Navigation("TrainingSystem");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.GraduationThesis", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Class", "Class")
                        .WithMany("GraduationTheses")
                        .HasForeignKey("ClassID");

                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("GraduationTheses")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Class");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Lecturer", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Position", "Position")
                        .WithMany("Lecturers")
                        .HasForeignKey("PositionID");

                    b.HasOne("LecturerManagement.Core.Models.Entities.StandardTime", "StandardTime")
                        .WithMany("Lecturers")
                        .HasForeignKey("StandardTimeID");

                    b.HasOne("LecturerManagement.Core.Models.Entities.SubjectDepartment", "SubjectDepartment")
                        .WithMany("Lecturers")
                        .HasForeignKey("SubjectDepartmentID");

                    b.Navigation("Position");

                    b.Navigation("StandardTime");

                    b.Navigation("SubjectDepartment");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.LecturerScientificResearch", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("LecturerScientificResearches")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.MachineRoom", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("MachineRooms")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.ScientificResearchGuide", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("ScientificResearchGuides")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Subject", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeID");

                    b.HasOne("LecturerManagement.Core.Models.Entities.TrainingSystem", "TrainingSystem")
                        .WithMany("Subjects")
                        .HasForeignKey("TrainingSystemID");

                    b.Navigation("SubjectType");

                    b.Navigation("TrainingSystem");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Teaching", b =>
                {
                    b.HasOne("LecturerManagement.Core.Models.Entities.Class", "Class")
                        .WithMany("Teachings")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturerManagement.Core.Models.Entities.Lecturer", "Lecturer")
                        .WithMany("Teaches")
                        .HasForeignKey("LectureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturerManagement.Core.Models.Entities.Subject", "Subject")
                        .WithMany("Teachings")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Class", b =>
                {
                    b.Navigation("GraduationTheses");

                    b.Navigation("Teachings");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Lecturer", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("AdvancedLearnings");

                    b.Navigation("GraduationTheses");

                    b.Navigation("LecturerScientificResearches");

                    b.Navigation("MachineRooms");

                    b.Navigation("ScientificResearchGuides");

                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Position", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.StandardTime", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.Subject", b =>
                {
                    b.Navigation("Teachings");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.SubjectDepartment", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LecturerManagement.Core.Models.Entities.TrainingSystem", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
