// <auto-generated />
using System;
using LecturerManagermentCodeFirst.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LecturerManagermentCodeFirst.API.Migrations
{
    [DbContext(typeof(LecturerManagermentSystemDbContext))]
    partial class LecturerManagermentSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Account", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.HasIndex("LecturerID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.AdvancedLearning", b =>
                {
                    b.Property<int>("AdvancedLearningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvancedLearningID");

                    b.HasIndex("LecturerID");

                    b.ToTable("AdvancedLearnings");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Class", b =>
                {
                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormsOfTraining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSutdent")
                        .HasColumnType("int");

                    b.Property<string>("TrainingSystemID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassID");

                    b.HasIndex("TrainingSystemID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.DynamicClassFactor", b =>
                {
                    b.Property<string>("DynamicClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.Property<int?>("FromDynamic")
                        .HasColumnType("int");

                    b.Property<string>("TeachesForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToDynamic")
                        .HasColumnType("int");

                    b.HasKey("DynamicClassID");

                    b.ToTable("DynamicClassFactors");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.GraduationThesis", b =>
                {
                    b.Property<int>("GraduationThesisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MarkSessionNumbers")
                        .HasColumnType("int");

                    b.Property<int?>("RebuttalProjectNumbers")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopicNumbers")
                        .HasColumnType("int");

                    b.HasKey("GraduationThesisID");

                    b.HasIndex("ClassID");

                    b.HasIndex("LecturerID");

                    b.ToTable("GraduationTheses");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Lecturer", b =>
                {
                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AcademicLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardTimeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectDepartmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YearStartWork")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LecturerID");

                    b.HasIndex("PositionID");

                    b.HasIndex("StandardTimeID");

                    b.HasIndex("SubjectDepartmentID");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.LecturerScientificResearch", b =>
                {
                    b.Property<string>("TopicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LevelOfResearch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfResearchParticipation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicID");

                    b.HasIndex("LecturerID");

                    b.ToTable("LecturerScientificResearches");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.MachineRoom", b =>
                {
                    b.Property<string>("MachineRoomID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QantityRoom")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineRoomID");

                    b.HasIndex("LecturerID");

                    b.ToTable("MachineRooms");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Position", b =>
                {
                    b.Property<string>("PositionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.ScientificResearchGuide", b =>
                {
                    b.Property<string>("ScientificResearchGuideID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScientificResearchGuideID");

                    b.HasIndex("LecturerID");

                    b.ToTable("ScientificResearchGuides");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.StandardTime", b =>
                {
                    b.Property<string>("StandardTimeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardHours")
                        .HasColumnType("int");

                    b.Property<string>("StandardTimeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandardTimeID");

                    b.ToTable("StandardTimes");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Subject", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingSystemID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectID");

                    b.HasIndex("SubjectTypeID");

                    b.HasIndex("TrainingSystemID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.SubjectDepartment", b =>
                {
                    b.Property<string>("SubjectDepartmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectDepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectDepartmentID");

                    b.ToTable("SubjectDepartments");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.SubjectType", b =>
                {
                    b.Property<string>("SubjectTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectTypeID");

                    b.ToTable("SubjectTypes");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Teaching", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LectureID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LectureIDNavigationLecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID", "LectureID", "ClassID");

                    b.HasIndex("ClassID");

                    b.HasIndex("LectureIDNavigationLecturerID");

                    b.ToTable("Teachings");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.TrainingSystem", b =>
                {
                    b.Property<string>("TrainingSystemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLearningUnit")
                        .HasColumnType("int");

                    b.Property<string>("TrainingSystemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingSystemID");

                    b.ToTable("TrainingSystems");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Account", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("LecturerID");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.AdvancedLearning", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("AdvancedLearnings")
                        .HasForeignKey("LecturerID");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Class", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.TrainingSystem", "TrainingSystemIDNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("TrainingSystemID");

                    b.Navigation("TrainingSystemIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.GraduationThesis", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Class", "ClassIDNavigation")
                        .WithMany("GraduationTheses")
                        .HasForeignKey("ClassID");

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("GraduationTheses")
                        .HasForeignKey("LecturerID");

                    b.Navigation("ClassIDNavigation");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Lecturer", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Position", "PositionIDNavigation")
                        .WithMany("Lecturers")
                        .HasForeignKey("PositionID");

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.StandardTime", "StandardTimeIDNavigation")
                        .WithMany("Lecturers")
                        .HasForeignKey("StandardTimeID");

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.SubjectDepartment", "SubjectDepartmentIDNavigations")
                        .WithMany("Lecturers")
                        .HasForeignKey("SubjectDepartmentID");

                    b.Navigation("PositionIDNavigation");

                    b.Navigation("StandardTimeIDNavigation");

                    b.Navigation("SubjectDepartmentIDNavigations");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.LecturerScientificResearch", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("LecturerScientificResearches")
                        .HasForeignKey("LecturerID");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.MachineRoom", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("MachineRooms")
                        .HasForeignKey("LecturerID");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.ScientificResearchGuide", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LecturerIDNavigation")
                        .WithMany("ScientificResearchGuides")
                        .HasForeignKey("LecturerID");

                    b.Navigation("LecturerIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Subject", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.SubjectType", "SubjectTypeIDNavigation")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeID");

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.TrainingSystem", "TrainingSystemIDNavigation")
                        .WithMany("Subjects")
                        .HasForeignKey("TrainingSystemID");

                    b.Navigation("SubjectTypeIDNavigation");

                    b.Navigation("TrainingSystemIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Teaching", b =>
                {
                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Class", "ClassIDNavigation")
                        .WithMany("Teachings")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Lecturer", "LectureIDNavigation")
                        .WithMany("Teaches")
                        .HasForeignKey("LectureIDNavigationLecturerID");

                    b.HasOne("LecturerManagermentCodeFirst.API.Entities.Subject", "SubjectIDNavigation")
                        .WithMany("Teaches")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassIDNavigation");

                    b.Navigation("LectureIDNavigation");

                    b.Navigation("SubjectIDNavigation");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Class", b =>
                {
                    b.Navigation("GraduationTheses");

                    b.Navigation("Teachings");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Lecturer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AdvancedLearnings");

                    b.Navigation("GraduationTheses");

                    b.Navigation("LecturerScientificResearches");

                    b.Navigation("MachineRooms");

                    b.Navigation("ScientificResearchGuides");

                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Position", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.StandardTime", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.Subject", b =>
                {
                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.SubjectDepartment", b =>
                {
                    b.Navigation("Lecturers");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LecturerManagermentCodeFirst.API.Entities.TrainingSystem", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
